- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - unzip
      - curl
    state: present

- name: Create consul user
  user:
    name: consul
    system: yes
    shell: /bin/false
    home: /etc/consul.d
    createhome: no

- name: Create consul directories
  file:
    path: "{{ item }}"
    state: directory
    owner: consul
    group: consul
    mode: '0755'
  loop:
    - /etc/consul.d
    - /opt/consul
    - /usr/local/bin

- name: Download Consul
  get_url:
    url: https://releases.hashicorp.com/consul/1.15.2/consul_1.15.2_linux_arm64.zip
    dest: /tmp/consul.zip

- name: Unzip Consul
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: consul
    group: consul
    mode: '0755'

- name: Copy Consul server configuration
  copy:
    src: consul_server.hcl
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: '0640'

- name: Create Consul systemd service
  copy:
    content: |
      [Unit]
      Description=Consul
      Documentation=https://www.consul.io/
      Requires=network-online.target
      After=network-online.target
      ConditionFileNotEmpty=/etc/consul.d/consul.hcl

      [Service]
      Type=notify
      User=consul
      Group=consul
      ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d/
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/consul.service
    mode: '0644'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start and enable Consul service
  systemd:
    name: consul
    state: started
    enabled: yes