version: "3.8"

services:
    rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - "15672:15672"
      expose:
        - "5672"
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
      networks:
      - app-network
      healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
          - "5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        networks:
            - app-network
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres"]
          interval: 10s
          timeout: 5s
          retries: 5

    session-service:
        build: ./session-service/
        depends_on:
          postgres:
            condition: service_healthy
        environment:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: users_db
        ports:
          - "8081:8081"
        networks:
          - app-network

    report-service:
      build: ./report-service/
      depends_on:
        postgres:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: statistics_db
        RABBIT_MQ_HOST: rabbitmq
        RABBIT_MQ_PORT: 5672
        RABBIT_MQ_USER: guest
        RABBIT_MQ_PASSWORD: guest
        RABBIT_MQ_QUEUE_NAME: messagequeue
        RABBIT_MQ_EXCHANGE: messagequeue-exchange
      expose:
        - "8086"
      networks:
        - app-network

    payment-service:
      build: ./payment-service/
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: payments_db
      expose:
        - "8084"
      networks:
        - app-network

    loyalty-service:
      build: ./loyalty-service/
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: balances_db
      expose:
        - "8085"
      networks:
        - app-network

    hotel-service:
      build: ./hotel-service/
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: hotels_db
      expose:
        - "8082"
      networks:
        - app-network

    gateway-service:
      build: ./gateway-service/
      depends_on:
        - session-service
        - hotel-service
        - booking-service
        - loyalty-service
        - report-service
        - payment-service
      environment:
        SESSION_SERVICE_HOST: session-service
        SESSION_SERVICE_PORT: 8081
        HOTEL_SERVICE_HOST: hotel-service
        HOTEL_SERVICE_PORT: 8082
        BOOKING_SERVICE_HOST: booking-service
        BOOKING_SERVICE_PORT: 8083
        PAYMENT_SERVICE_HOST: payment-service
        PAYMENT_SERVICE_PORT: 8084
        LOYALTY_SERVICE_HOST: loyalty-service
        LOYALTY_SERVICE_PORT: 8085
        REPORT_SERVICE_HOST: report-service
        REPORT_SERVICE_PORT: 8086
      ports:
        - "8087:8087"
      networks:
        - app-network

    booking-service:
      build: ./booking-service/
      depends_on:
        postgres:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: reservations_db
        RABBIT_MQ_HOST: rabbitmq
        RABBIT_MQ_PORT: 5672
        RABBIT_MQ_USER: guest
        RABBIT_MQ_PASSWORD: guest
        RABBIT_MQ_QUEUE_NAME: messagequeue
        RABBIT_MQ_EXCHANGE: messagequeue-exchange
        HOTEL_SERVICE_HOST: hotel-service
        HOTEL_SERVICE_PORT: 8082
        PAYMENT_SERVICE_HOST: payment-service
        PAYMENT_SERVICE_PORT: 8084
        LOYALTY_SERVICE_HOST: loyalty-service
        LOYALTY_SERVICE_PORT: 8085
      expose:
        - "8083"
      networks:
        - app-network
volumes:
  db:
  postgres-data:

networks:
  app-network: