- hosts: node01
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copy app
      copy:
        src: /home/vagrant/services/
        dest: /home/vagrant/services/

    - name: Start app
      shell: docker-compose up -d
      args:
        chdir: /home/vagrant/services/