[consul_servers]
consul_server ansible_host=192.168.57.10 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa

[consul_clients]
api ansible_host=192.168.57.11 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa
db ansible_host=192.168.57.12 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa

[api_servers]
api

[databases]
db

[managers]
manager ansible_host=192.168.57.13 ansible_user=vagrant ansible_ssh_private_key_file=~/.ssh/id_rsa