Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
  end

  config.vm.define "consul_server" do |consul|
    consul.vm.hostname = "consul-server"
    consul.vm.network "private_network", ip: "192.168.57.10"
    consul.vm.network "forwarded_port", guest: 8500, host: 8500  # Consul UI
  end

  config.vm.define "api" do |api|
    api.vm.hostname = "api"
    api.vm.network "private_network", ip: "192.168.57.11"
    api.vm.network "forwarded_port", guest: 8082, host: 8082  # Hotel service
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.57.12"
  end

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.57.13"
  end
end